# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='oauth_token',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='oauth_token_secret',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
