# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170425_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uid',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
